ŸØÇÅŸ¥Éô*Ÿ±Çbsdy√"""
=======================
TickedStroke patheffect
=======================

Matplotlib's :mod:`.patheffects` can be used to alter the way paths
are drawn at a low enough level that they can affect almost anything.

The :doc:`patheffects guide</tutorials/advanced/patheffects_guide>`
details the use of patheffects.

The `~matplotlib.patheffects.TickedStroke` patheffect illustrated here
draws a path with a ticked style.  The spacing, length, and angle of
ticks can be controlled.

See also the :doc:`contour demo example
</gallery/lines_bars_and_markers/lines_with_ticks_demo>`.

See also the :doc:`contours in optimization example
</gallery/images_contours_and_fields/contours_in_optimization_demo>`.
"""Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Çbc1xO###############################################################################Ÿ±Ç`a
Ÿ±Çbc1x # Applying TickedStroke to pathsŸ±Ç`a
Ÿ±Çbc1x # ==============================Ÿ±Ç`a
Ÿ±ÇbknfimportŸ±Ç`a Ÿ±ÇbnnŸ¢ÑjmatplotlibŸ†Ñjmatplotlibe3.5.1fmodulejmatplotlibfmoduleıŸ±Çbnna.Ÿ±ÇbnngpatchesŸ±Ç`a Ÿ±ÇakbasŸ±Ç`a Ÿ±ÇbnngpatchesŸ±Ç`a
Ÿ±ÇbkndfromŸ±Ç`a Ÿ±ÇbnnŸ¢ÑjmatplotlibŸ†Ñjmatplotlibe3.5.1fmodulejmatplotlibfmoduleıŸ±Çbnna.Ÿ±ÇbnndpathŸ±Ç`a Ÿ±ÇbknfimportŸ±Ç`a Ÿ±Ç`dPathŸ±Ç`a
Ÿ±ÇbknfimportŸ±Ç`a Ÿ±ÇbnnŸ¢ÑenumpyŸ†Ñenumpyf1.22.3fmoduleenumpyfmoduleıŸ±Ç`a Ÿ±ÇakbasŸ±Ç`a Ÿ±ÇbnnbnpŸ±Ç`a
Ÿ±ÇbknfimportŸ±Ç`a Ÿ±ÇbnnŸ¢ÑjmatplotlibŸ†Ñjmatplotlibe3.5.1fmodulejmatplotlibfmoduleıŸ±Çbnna.Ÿ±ÇbnnfpyplotŸ±Ç`a Ÿ±ÇakbasŸ±Ç`a Ÿ±ÇbnncpltŸ±Ç`a
Ÿ±ÇbknfimportŸ±Ç`a Ÿ±ÇbnnŸ¢ÑjmatplotlibŸ†Ñjmatplotlibe3.5.1fmodulejmatplotlibfmoduleıŸ±Çbnna.Ÿ±ÇbnnkpatheffectsŸ±Ç`a Ÿ±ÇakbasŸ±Ç`a Ÿ±ÇbnnkpatheffectsŸ±Ç`a
Ÿ±Ç`a
Ÿ±Ç`cfigŸ±Ç`a,Ÿ±Ç`a Ÿ±Ç`baxŸ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Ç`cpltŸ±Çaoa.Ÿ±Ç`hsubplotsŸ±Ç`a(Ÿ±Ç`gfigsizeŸ±Çaoa=Ÿ±Ç`a(Ÿ±Çbmia6Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmia6Ÿ±Ç`a)Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`dpathŸ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Ç`dPathŸ±Çaoa.Ÿ±Ç`kunit_circleŸ±Ç`a(Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`epatchŸ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Ç`gpatchesŸ±Çaoa.Ÿ±Ç`iPathPatchŸ±Ç`a(Ÿ±Ç`dpathŸ±Ç`a,Ÿ±Ç`a Ÿ±Ç`ifacecolorŸ±Çaoa=Ÿ±Çbs1a'Ÿ±Çbs1dnoneŸ±Çbs1a'Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`blwŸ±Çaoa=Ÿ±Çbmia2Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`lpath_effectsŸ±Çaoa=Ÿ±Ç`a[Ÿ±Ç`a
Ÿ±Ç`d    Ÿ±Ç`kpatheffectsŸ±Çaoa.Ÿ±Ç`pwithTickedStrokeŸ±Ç`a(Ÿ±Ç`eangleŸ±Çaoa=Ÿ±Çaoa-Ÿ±Çbmib90Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`gspacingŸ±Çaoa=Ÿ±Çbmib10Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`flengthŸ±Çaoa=Ÿ±Çbmia1Ÿ±Ç`a)Ÿ±Ç`a]Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Ç`baxŸ±Çaoa.Ÿ±Ç`iadd_patchŸ±Ç`a(Ÿ±Ç`epatchŸ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`baxŸ±Çaoa.Ÿ±Ç`daxisŸ±Ç`a(Ÿ±Çbs1a'Ÿ±Çbs1eequalŸ±Çbs1a'Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`baxŸ±Çaoa.Ÿ±Ç`hset_xlimŸ±Ç`a(Ÿ±Çaoa-Ÿ±Çbmia2Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmia2Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`baxŸ±Çaoa.Ÿ±Ç`hset_ylimŸ±Ç`a(Ÿ±Çaoa-Ÿ±Çbmia2Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmia2Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Ç`cpltŸ±Çaoa.Ÿ±Ç`dshowŸ±Ç`a(Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Çbc1xO###############################################################################Ÿ±Ç`a
Ÿ±Çbc1x # Applying TickedStroke to linesŸ±Ç`a
Ÿ±Çbc1x # ==============================Ÿ±Ç`a
Ÿ±Ç`cfigŸ±Ç`a,Ÿ±Ç`a Ÿ±Ç`baxŸ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Ç`cpltŸ±Çaoa.Ÿ±Ç`hsubplotsŸ±Ç`a(Ÿ±Ç`gfigsizeŸ±Çaoa=Ÿ±Ç`a(Ÿ±Çbmia6Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmia6Ÿ±Ç`a)Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`baxŸ±Çaoa.Ÿ±Ç`dplotŸ±Ç`a(Ÿ±Ç`a[Ÿ±Çbmia0Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmia1Ÿ±Ç`a]Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`a[Ÿ±Çbmia0Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmia1Ÿ±Ç`a]Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`elabelŸ±Çaoa=Ÿ±Çbs2a"Ÿ±Çbs2dLineŸ±Çbs2a"Ÿ±Ç`a,Ÿ±Ç`a
Ÿ±Ç`h        Ÿ±Ç`lpath_effectsŸ±Çaoa=Ÿ±Ç`a[Ÿ±Ç`kpatheffectsŸ±Çaoa.Ÿ±Ç`pwithTickedStrokeŸ±Ç`a(Ÿ±Ç`gspacingŸ±Çaoa=Ÿ±Çbmia7Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`eangleŸ±Çaoa=Ÿ±Çbmic135Ÿ±Ç`a)Ÿ±Ç`a]Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Ç`bnxŸ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Çbmic101Ÿ±Ç`a
Ÿ±Ç`axŸ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Ç`bnpŸ±Çaoa.Ÿ±Ç`hlinspaceŸ±Ç`a(Ÿ±Çbmfc0.0Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmfc1.0Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`bnxŸ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`ayŸ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Çbmfc0.3Ÿ±Çaoa*Ÿ±Ç`bnpŸ±Çaoa.Ÿ±Ç`csinŸ±Ç`a(Ÿ±Ç`axŸ±Çaoa*Ÿ±Çbmia8Ÿ±Ç`a)Ÿ±Ç`a Ÿ±Çaoa+Ÿ±Ç`a Ÿ±Çbmfc0.4Ÿ±Ç`a
Ÿ±Ç`baxŸ±Çaoa.Ÿ±Ç`dplotŸ±Ç`a(Ÿ±Ç`axŸ±Ç`a,Ÿ±Ç`a Ÿ±Ç`ayŸ±Ç`a,Ÿ±Ç`a Ÿ±Ç`elabelŸ±Çaoa=Ÿ±Çbs2a"Ÿ±Çbs2eCurveŸ±Çbs2a"Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`lpath_effectsŸ±Çaoa=Ÿ±Ç`a[Ÿ±Ç`kpatheffectsŸ±Çaoa.Ÿ±Ç`pwithTickedStrokeŸ±Ç`a(Ÿ±Ç`a)Ÿ±Ç`a]Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Ç`baxŸ±Çaoa.Ÿ±Ç`flegendŸ±Ç`a(Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Ç`cpltŸ±Çaoa.Ÿ±Ç`dshowŸ±Ç`a(Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Çbc1xO###############################################################################Ÿ±Ç`a
Ÿ±Çbc1x(# Applying TickedStroke to contour plotsŸ±Ç`a
Ÿ±Çbc1x(# ======================================Ÿ±Ç`a
Ÿ±Çbc1a#Ÿ±Ç`a
Ÿ±Çbc1x.# Contour plot with objective and constraints.Ÿ±Ç`a
Ÿ±Çbc1xE# Curves generated by contour to represent a typical constraint in anŸ±Ç`a
Ÿ±Çbc1xE# optimization problem should be plotted with angles between zero andŸ±Ç`a
Ÿ±Çbc1n# 180 degrees.Ÿ±Ç`a
Ÿ±Ç`cfigŸ±Ç`a,Ÿ±Ç`a Ÿ±Ç`baxŸ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Ç`cpltŸ±Çaoa.Ÿ±Ç`hsubplotsŸ±Ç`a(Ÿ±Ç`gfigsizeŸ±Çaoa=Ÿ±Ç`a(Ÿ±Çbmia6Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmia6Ÿ±Ç`a)Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Ç`bnxŸ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Çbmic101Ÿ±Ç`a
Ÿ±Ç`bnyŸ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Çbmic105Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Çbc1w# Set up survey vectorsŸ±Ç`a
Ÿ±Ç`dxvecŸ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Ç`bnpŸ±Çaoa.Ÿ±Ç`hlinspaceŸ±Ç`a(Ÿ±Çbmfe0.001Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmfc4.0Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`bnxŸ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`dyvecŸ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Ç`bnpŸ±Çaoa.Ÿ±Ç`hlinspaceŸ±Ç`a(Ÿ±Çbmfe0.001Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmfc4.0Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`bnyŸ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Çbc1x># Set up survey matrices.  Design disk loading and gear ratio.Ÿ±Ç`a
Ÿ±Ç`bx1Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`bx2Ÿ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Ç`bnpŸ±Çaoa.Ÿ±Ç`hmeshgridŸ±Ç`a(Ÿ±Ç`dxvecŸ±Ç`a,Ÿ±Ç`a Ÿ±Ç`dyvecŸ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Çbc1x# Evaluate some stuff to plotŸ±Ç`a
Ÿ±Ç`cobjŸ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Ç`bx1Ÿ±Çaoa*Ÿ±Çaoa*Ÿ±Çbmia2Ÿ±Ç`a Ÿ±Çaoa+Ÿ±Ç`a Ÿ±Ç`bx2Ÿ±Çaoa*Ÿ±Çaoa*Ÿ±Çbmia2Ÿ±Ç`a Ÿ±Çaoa-Ÿ±Ç`a Ÿ±Çbmia2Ÿ±Çaoa*Ÿ±Ç`bx1Ÿ±Ç`a Ÿ±Çaoa-Ÿ±Ç`a Ÿ±Çbmia2Ÿ±Çaoa*Ÿ±Ç`bx2Ÿ±Ç`a Ÿ±Çaoa+Ÿ±Ç`a Ÿ±Çbmia2Ÿ±Ç`a
Ÿ±Ç`bg1Ÿ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Çaoa-Ÿ±Ç`a(Ÿ±Çbmia3Ÿ±Çaoa*Ÿ±Ç`bx1Ÿ±Ç`a Ÿ±Çaoa+Ÿ±Ç`a Ÿ±Ç`bx2Ÿ±Ç`a Ÿ±Çaoa-Ÿ±Ç`a Ÿ±Çbmfc5.5Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`bg2Ÿ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Çaoa-Ÿ±Ç`a(Ÿ±Ç`bx1Ÿ±Ç`a Ÿ±Çaoa+Ÿ±Ç`a Ÿ±Çbmia2Ÿ±Çaoa*Ÿ±Ç`bx2Ÿ±Ç`a Ÿ±Çaoa-Ÿ±Ç`a Ÿ±Çbmfc4.5Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`bg3Ÿ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Çbmfc0.8Ÿ±Ç`a Ÿ±Çaoa+Ÿ±Ç`a Ÿ±Ç`bx1Ÿ±Çaoa*Ÿ±Çaoa*Ÿ±Çaoa-Ÿ±Çbmia3Ÿ±Ç`a Ÿ±Çaoa-Ÿ±Ç`a Ÿ±Ç`bx2Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Ç`dcntrŸ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Ç`baxŸ±Çaoa.Ÿ±Ç`gcontourŸ±Ç`a(Ÿ±Ç`bx1Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`bx2Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`cobjŸ±Ç`a,Ÿ±Ç`a Ÿ±Ç`a[Ÿ±Çbmfd0.01Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmfc0.1Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmfc0.5Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmia1Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmia2Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmia4Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmia8Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmib16Ÿ±Ç`a]Ÿ±Ç`a,Ÿ±Ç`a
Ÿ±Ç`r                  Ÿ±Ç`fcolorsŸ±Çaoa=Ÿ±Çbs1a'Ÿ±Çbs1eblackŸ±Çbs1a'Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`baxŸ±Çaoa.Ÿ±Ç`fclabelŸ±Ç`a(Ÿ±Ç`dcntrŸ±Ç`a,Ÿ±Ç`a Ÿ±Ç`cfmtŸ±Çaoa=Ÿ±Çbs2a"Ÿ±Çbsie%2.1fŸ±Çbs2a"Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`nuse_clabeltextŸ±Çaoa=Ÿ±ÇbkcdTrueŸ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Ç`ccg1Ÿ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Ç`baxŸ±Çaoa.Ÿ±Ç`gcontourŸ±Ç`a(Ÿ±Ç`bx1Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`bx2Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`bg1Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`a[Ÿ±Çbmia0Ÿ±Ç`a]Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`fcolorsŸ±Çaoa=Ÿ±Çbs1a'Ÿ±Çbs1jsandybrownŸ±Çbs1a'Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`cpltŸ±Çaoa.Ÿ±Ç`dsetpŸ±Ç`a(Ÿ±Ç`ccg1Ÿ±Çaoa.Ÿ±Ç`kcollectionsŸ±Ç`a,Ÿ±Ç`a
Ÿ±Ç`i         Ÿ±Ç`lpath_effectsŸ±Çaoa=Ÿ±Ç`a[Ÿ±Ç`kpatheffectsŸ±Çaoa.Ÿ±Ç`pwithTickedStrokeŸ±Ç`a(Ÿ±Ç`eangleŸ±Çaoa=Ÿ±Çbmic135Ÿ±Ç`a)Ÿ±Ç`a]Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Ç`ccg2Ÿ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Ç`baxŸ±Çaoa.Ÿ±Ç`gcontourŸ±Ç`a(Ÿ±Ç`bx1Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`bx2Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`bg2Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`a[Ÿ±Çbmia0Ÿ±Ç`a]Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`fcolorsŸ±Çaoa=Ÿ±Çbs1a'Ÿ±Çbs1iorangeredŸ±Çbs1a'Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`cpltŸ±Çaoa.Ÿ±Ç`dsetpŸ±Ç`a(Ÿ±Ç`ccg2Ÿ±Çaoa.Ÿ±Ç`kcollectionsŸ±Ç`a,Ÿ±Ç`a
Ÿ±Ç`i         Ÿ±Ç`lpath_effectsŸ±Çaoa=Ÿ±Ç`a[Ÿ±Ç`kpatheffectsŸ±Çaoa.Ÿ±Ç`pwithTickedStrokeŸ±Ç`a(Ÿ±Ç`eangleŸ±Çaoa=Ÿ±Çbmib60Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`flengthŸ±Çaoa=Ÿ±Çbmia2Ÿ±Ç`a)Ÿ±Ç`a]Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Ç`ccg3Ÿ±Ç`a Ÿ±Çaoa=Ÿ±Ç`a Ÿ±Ç`baxŸ±Çaoa.Ÿ±Ç`gcontourŸ±Ç`a(Ÿ±Ç`bx1Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`bx2Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`bg3Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`a[Ÿ±Çbmia0Ÿ±Ç`a]Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Ç`fcolorsŸ±Çaoa=Ÿ±Çbs1a'Ÿ±Çbs1jmediumblueŸ±Çbs1a'Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`cpltŸ±Çaoa.Ÿ±Ç`dsetpŸ±Ç`a(Ÿ±Ç`ccg3Ÿ±Çaoa.Ÿ±Ç`kcollectionsŸ±Ç`a,Ÿ±Ç`a
Ÿ±Ç`i         Ÿ±Ç`lpath_effectsŸ±Çaoa=Ÿ±Ç`a[Ÿ±Ç`kpatheffectsŸ±Çaoa.Ÿ±Ç`pwithTickedStrokeŸ±Ç`a(Ÿ±Ç`gspacingŸ±Çaoa=Ÿ±Çbmia7Ÿ±Ç`a)Ÿ±Ç`a]Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Ç`baxŸ±Çaoa.Ÿ±Ç`hset_xlimŸ±Ç`a(Ÿ±Çbmia0Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmia4Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`baxŸ±Çaoa.Ÿ±Ç`hset_ylimŸ±Ç`a(Ÿ±Çbmia0Ÿ±Ç`a,Ÿ±Ç`a Ÿ±Çbmia4Ÿ±Ç`a)Ÿ±Ç`a
Ÿ±Ç`a
Ÿ±Ç`cpltŸ±Çaoa.Ÿ±Ç`dshowŸ±Ç`a(Ÿ±Ç`a)Ÿ±Ç`a
`dNoneˆ