Ùª­jAttributesÙ¯‚€öpExtended SummaryÙ¯‚Ù¹‚˜Ù§x0Returns the factors of the polar decomposition  Ù¢„auÙ „ööelocalauelocalõÙ§e and Ù¢„apÙ „ööelocalapelocalõÙ§k such that Ù¡fa = upÙ§e (if Ù¢„dsideÙ „ööelocaldsideelocalõÙ§p is "right") or Ù¡fa = puÙ§e (if Ù¢„dsideÙ „ööelocaldsideelocalõÙ§s is "left"), where Ù¢„apÙ „ööelocalapelocalõÙ§x5 is positive semidefinite. Depending on the shape of Ù¢„aaÙ „ööelocalaaelocalõÙ§x , either the rows or columns of Ù¢„auÙ „ööelocalauelocalõÙ§w are orthonormal. When Ù¢„aaÙ „ööelocalaaelocalõÙ§t is a square array, Ù¢„auÙ „ööelocalauelocalõÙ§x! is a square unitary array. When Ù¢„aaÙ „ööelocalaaelocalõÙ§xA is not square, the "canonical polar decomposition"  is computed.€ögMethodsÙ¯‚€öeNotesÙ¯‚€öpOther ParametersÙ¯‚€öjParametersÙ¯‚‚Ù°ƒaaq(m, n) array_likeÙ¹‚Ù§xThe array to be factored.€Ù°ƒdsidex{'left', 'right'}, optionalÙ¹‚‰Ù§xGDetermines whether a right or left polar decomposition is computed. If Ù¢„dsideÙ „ööelocaldsideelocalõÙ§r is "right", then Ù¡fa = upÙ§f.  If Ù¢„dsideÙ „ööelocaldsideelocalõÙ§r is "left",  then Ù¡fa = puÙ§x.  The default is "right".€öfRaisesÙ¯‚€öhReceivesÙ¯‚€ögReturnsÙ¯‚‚Ù°ƒaun(m, n) ndarrayÙ¹‚‰Ù§cIf Ù¢„aaÙ „ööelocalaaelocalõÙ§q is square, then Ù¢„auÙ „ööelocalauelocalõÙ§x+ is unitary. If m > n, then the columns of Ù¢„aaÙ „ööelocalaaelocalõÙ§x1 are orthonormal, and if m < n, then the rows of Ù¢„auÙ „ööelocalauelocalõÙ§q are orthonormal.€Ù°ƒapgndarrayÙ¹‚ŠÙ¢„apÙ „ööelocalapelocalõÙ§x( is Hermitian positive semidefinite. If Ù¢„aaÙ „ööelocalaaelocalõÙ§q is nonsingular, Ù¢„apÙ „ööelocalapelocalõÙ§x$ is positive definite. The shape of Ù¢„apÙ „ööelocalapelocalõÙ§x+ is (n, n) or (m, m), depending on whether Ù¢„dsideÙ „ööelocaldsideelocalõÙ§x$ is "right" or "left", respectively.€ögSummaryÙ¯‚Ù¹‚Ù§x Compute the polar decomposition.€öhWarningsÙ¯‚€öeWarnsÙ¯‚€öfYieldsÙ¯‚€ö†gSummarypExtended SummaryjParametersgReturnsjReferenceshExamplesx/scipy/linalg/_decomp_polar.pyr<class 'function'>x)scipy.signal._lti_conversion.linalg.polarÙ¯‚ŒÙ´ƒ˜2Ù±‚bkndfromÙ±‚`a Ù±‚bnnÙ¢„escipyÙ „escipye1.8.0fmoduleescipyfmoduleõÙ±‚bnna.Ù±‚bnnÙ¢„flinalgÙ „escipye1.8.0fmodulelscipy.linalgfmoduleõÙ±‚`a Ù±‚bknfimportÙ±‚`a Ù±‚`Ù¢„epolarÙ „escipye1.8.0fmodulex scipy.linalg._decomp_polar.polarfmoduleõÙ±‚`a
Ù±‚`Ù¢„aaÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚`a Ù±‚aoa=Ù±‚`a Ù±‚`Ù¢„bnpÙ „enumpyf1.22.3fmoduleenumpyfmoduleõÙ±‚aoa.Ù±‚`Ù¢„earrayÙ „enumpyf1.22.3fmoduleknumpy.arrayfmoduleõÙ±‚`a(Ù±‚`a[Ù±‚`a[Ù±‚bmia1Ù±‚`a,Ù±‚`a Ù±‚aoa-Ù±‚bmia1Ù±‚`a]Ù±‚`a,Ù±‚`a Ù±‚`a[Ù±‚bmia2Ù±‚`a,Ù±‚`a Ù±‚bmia4Ù±‚`a]Ù±‚`a]Ù±‚`a)Ù±‚`a
Ù±‚`auÙ±‚`a,Ù±‚`a Ù±‚`apÙ±‚`a Ù±‚aoa=Ù±‚`a Ù±‚`Ù¢„epolarÙ „escipye1.8.0fmodulex scipy.linalg._decomp_polar.polarfmoduleõÙ±‚`a(Ù±‚`Ù¢„aaÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚`a)Ù±‚`a
Ù±‚`Ù¢„auÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõxFarray([[ 0.85749293, -0.51449576],
       [ 0.51449576,  0.85749293]])fexecedÙ´ƒÙ±‚`Ù¢„apÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõxFarray([[ 1.88648444,  1.2004901 ],
       [ 1.2004901 ,  3.94446746]])fexecedÙ¹‚Ù§x!A non-square example, with m < n:€Ù´ƒ˜-Ù±‚`Ù¢„abÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚`a Ù±‚aoa=Ù±‚`a Ù±‚`Ù¢„bnpÙ „enumpyf1.22.3fmoduleenumpyfmoduleõÙ±‚aoa.Ù±‚`Ù¢„earrayÙ „enumpyf1.22.3fmoduleknumpy.arrayfmoduleõÙ±‚`a(Ù±‚`a[Ù±‚`a[Ù±‚bmfc0.5Ù±‚`a,Ù±‚`a Ù±‚bmia1Ù±‚`a,Ù±‚`a Ù±‚bmia2Ù±‚`a]Ù±‚`a,Ù±‚`a Ù±‚`a[Ù±‚bmfc1.5Ù±‚`a,Ù±‚`a Ù±‚bmia3Ù±‚`a,Ù±‚`a Ù±‚bmia4Ù±‚`a]Ù±‚`a]Ù±‚`a)Ù±‚`a
Ù±‚`auÙ±‚`a,Ù±‚`a Ù±‚`apÙ±‚`a Ù±‚aoa=Ù±‚`a Ù±‚`Ù¢„epolarÙ „escipye1.8.0fmodulex scipy.linalg._decomp_polar.polarfmoduleõÙ±‚`a(Ù±‚`Ù¢„abÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚`a)Ù±‚`a
Ù±‚`Ù¢„auÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõx`array([[-0.21196618, -0.42393237,  0.88054056],
       [ 0.39378971,  0.78757942,  0.4739708 ]])fexecedÙ´ƒÙ±‚`Ù¢„apÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõxarray([[ 0.48470147,  0.96940295,  1.15122648],
       [ 0.96940295,  1.9388059 ,  2.30245295],
       [ 1.15122648,  2.30245295,  3.65696431]])fexecedÙ´ƒˆÙ±‚`Ù¢„auÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚aoa.Ù±‚`cdotÙ±‚`a(Ù±‚`Ù¢„apÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚`a)Ù±‚`c   Ù±‚bc1x# Verify the decomposition.x6array([[ 0.5,  1. ,  2. ],
       [ 1.5,  3. ,  4. ]])fexecedÙ´ƒŠÙ±‚`Ù¢„auÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚aoa.Ù±‚`cdotÙ±‚`a(Ù±‚`Ù¢„auÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚aoa.Ù±‚`Ù¢„aTÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚`a)Ù±‚`c   Ù±‚bc1x # The rows of u are orthonormal.xZarray([[  1.00000000e+00,  -2.07353665e-17],
       [ -2.07353665e-17,   1.00000000e+00]])fexecedÙ¹‚Ù§x'Another non-square example, with m > n:€Ù´ƒ•Ù±‚`acÙ±‚`a Ù±‚aoa=Ù±‚`a Ù±‚`Ù¢„abÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚aoa.Ù±‚`aTÙ±‚`a
Ù±‚`auÙ±‚`a,Ù±‚`a Ù±‚`apÙ±‚`a Ù±‚aoa=Ù±‚`a Ù±‚`Ù¢„epolarÙ „escipye1.8.0fmodulex scipy.linalg._decomp_polar.polarfmoduleõÙ±‚`a(Ù±‚`acÙ±‚`a)Ù±‚`a
Ù±‚`Ù¢„auÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõxiarray([[-0.21196618,  0.39378971],
       [-0.42393237,  0.78757942],
       [ 0.88054056,  0.4739708 ]])fexecedÙ´ƒÙ±‚`Ù¢„apÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõxFarray([[ 1.23116567,  1.93241587],
       [ 1.93241587,  4.84930602]])fexecedÙ´ƒˆÙ±‚`Ù¢„auÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚aoa.Ù±‚`cdotÙ±‚`a(Ù±‚`Ù¢„apÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚`a)Ù±‚`c   Ù±‚bc1x# Verify the decomposition.x?array([[ 0.5,  1.5],
       [ 1. ,  3. ],
       [ 2. ,  4. ]])fexecedÙ´ƒŠÙ±‚`Ù¢„auÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚aoa.Ù±‚`Ù¢„aTÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚aoa.Ù±‚`cdotÙ±‚`a(Ù±‚`Ù¢„auÙ „enumpyf1.22.3fmodulemnumpy.ndarrayfmoduleõÙ±‚`a)Ù±‚`b  Ù±‚bc1x## The columns of u are orthonormal.xZarray([[  1.00000000e+00,  -1.26363763e-16],
       [ -1.26363763e-16,   1.00000000e+00]])fexecedö€e1.8.0Ù«vpolar(a, side='right')öx scipy.linalg._decomp_polar.polar€